//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DistribuidoraPacificoEntities : DbContext
    {
        public DistribuidoraPacificoEntities()
            : base("name=DistribuidoraPacificoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblContactos> TblContactos { get; set; }
        public virtual DbSet<TblDetalleFactura> TblDetalleFactura { get; set; }
        public virtual DbSet<TblFactura> TblFactura { get; set; }
        public virtual DbSet<TblProducto> TblProducto { get; set; }
        public virtual DbSet<TblProductosProveedor> TblProductosProveedor { get; set; }
        public virtual DbSet<TblProveedores> TblProveedores { get; set; }
        public virtual DbSet<TblRoles> TblRoles { get; set; }
        public virtual DbSet<TblUsuarios> TblUsuarios { get; set; }
    }
}
