//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFactura()
        {
            this.TblDetalleFactura = new HashSet<TblDetalleFactura>();
        }
    
        public int codigoFactura { get; set; }
        public string cedulaCliente { get; set; }
        public decimal TotalPagar { get; set; }
        public string formaPago { get; set; }
        public Nullable<decimal> informacionPago { get; set; }
        public decimal descuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDetalleFactura> TblDetalleFactura { get; set; }
        public virtual TblUsuarios TblUsuarios { get; set; }
        public virtual TblUsuarios TblUsuarios1 { get; set; }
        public virtual TblUsuarios TblUsuarios2 { get; set; }
    }
}
