//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductosProveedor
    {
        public string codBarras { get; set; }
        public string cedLegal { get; set; }
    
        public virtual TblProducto TblProducto { get; set; }
        public virtual TblProducto TblProducto1 { get; set; }
        public virtual TblProducto TblProducto2 { get; set; }
        public virtual TblProducto TblProducto3 { get; set; }
        public virtual TblProveedores TblProveedores { get; set; }
        public virtual TblProveedores TblProveedores1 { get; set; }
        public virtual TblProveedores TblProveedores2 { get; set; }
        public virtual TblProveedores TblProveedores3 { get; set; }
    }
}
