//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProducto()
        {
            this.TblDetalleFactura = new HashSet<TblDetalleFactura>();
            this.TblDetalleFactura1 = new HashSet<TblDetalleFactura>();
            this.TblDetalleFactura2 = new HashSet<TblDetalleFactura>();
            this.TblProductosProveedor = new HashSet<TblProductosProveedor>();
            this.TblProductosProveedor1 = new HashSet<TblProductosProveedor>();
            this.TblProductosProveedor2 = new HashSet<TblProductosProveedor>();
            this.TblProductosProveedor3 = new HashSet<TblProductosProveedor>();
        }
    
        public string codBarras { get; set; }
        public string clasificacion { get; set; }
        public string descripcion { get; set; }
        public decimal precioCompra { get; set; }
        public decimal porcentajeIV { get; set; }
        public decimal porcentajeIVA { get; set; }
        public bool exento { get; set; }
        public string unidadMedida { get; set; }
        public bool estado { get; set; }
        public string foto { get; set; }
        public decimal precioImpuestoIncluido { get; set; }
        public int cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDetalleFactura> TblDetalleFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDetalleFactura> TblDetalleFactura1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblDetalleFactura> TblDetalleFactura2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosProveedor> TblProductosProveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosProveedor> TblProductosProveedor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosProveedor> TblProductosProveedor2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductosProveedor> TblProductosProveedor3 { get; set; }
    }
}
